### ISSUE TITLE
Publishables are broken when listed in nested categories

### ISSUE THREAD

**Issue by JirkaChadima** [ella/ella#101]
### Description

This was tested in Ella 3.0.0.

We have following category structure:

```
/
/category1/
/category1/category2/
```

And (at least) **three** articles that are listed in both category1 and category2. When you access `/category1/`, ella gets stuck in an infinite loop.

The problem seems to be in `ella.core.managers.ListingManager.get_listing` method where the total `count` of listings can be greater than all possible distinct publishables. For less then 3 articles listed in the same fashion, the code works OK (Because of the magic padding/skip constant).

I think the solution would be to change the `count` variable in said method to something like:

```
distinct = qset.filter(category=category).distinct().count()
count = min(distinct, count)
```

**Comment by honzakral** [comment]
If you could provide a test case for this example we can work out a solution. Using distinct queryset is not acceptable.

Thanks

**Comment by JirkaChadima** [comment]
Just quick and dirty in gist. This should produce an infinite loop as described above.

https://gist.github.com/2925237
