### ISSUE TITLE
separate boxes from ella.core

### ISSUE THREAD

**Issue by jan-matejka** [ella/ella#104]
So boxes can be used without the rest of ella apps.

**Comment by jan-matejka** [comment]
I had changed all (hopefully) references to ella.core.box to ella.box.box. But I dont know about 64ba90ac0a7511dbaf48af8077347438a4ccd52e/ella/core/conf.py#L14-15 as I dont see it referenced anywehre.

Tests are passing.
Tested manualy with django app but not ella app yet.
And I'm not quite sure about d2d784dd129ba7309ec121de8500bb7d5ed398eb.

suggestions?

**Comment by honzakral** [comment]
This won't work - there is no reason why you cannot use Box from outside of ella, it won't fuck up your environment (if it does, it's a bug and we should fix it) that you have a bunch of code that you don't use loaded in memory.

Even your proposed patch still loads all of ella.core into memory.

Closing for now unless you find a use case where you absolutely cannot have ella packages on disk.

**Comment by jan-matejka** [comment]
Without this patch I would need to add ella.core into INSTALLED_APPS, wouldnt I?

**Comment by honzakral** [comment]
You shouldn't need that and if you do this patch won't help.

Also if you do, let's fix it.
On Jul 10, 2012 11:08 PM, "yaccz" <
reply@reply.github.com>
wrote:

**Comment by jan-matejka** [comment]
How am I then supposted to use boxes when I dont't want to get ella.core models pulled in?

**Comment by honzakral** [comment]
Pulled in where? In memory? Why do you care? You shouldn't have to care at all, there is no reason to.

**Comment by jan-matejka** [comment]
To use boxes now, I need to have ella.core in installed apps, right? Then i'm getting ella.core.models into db and i don't like that.

**Comment by honzakral** [comment]
no, it doesn't have to be in installed apps, see my comment 15 days ago

**Comment by jan-matejka** [comment]
Then how am i supposted to get the box templatetag working?
Even if i import the ella.core.templatetags in myproject.templatetags i will hit the issue addressed in d2d784dd129ba7309ec121de8500bb7d5ed398eb

**Comment by honzakral** [comment]
So sorry, my bad - you are right.

Please update the patch using the hints I mentioned in the comments and I wil lhave a look at it and get it in.

Note that I also intent to purge all the stuff that's being pushed into the box's context ATM because it's bunch of special cases and any params of the box can be reached by {{ box.params.hatever }} anyway.

Thanks!

**Comment by jan-matejka** [comment]
Actually, I think it also needs better separation from the core because an issue manifested by failing to delete a django user due to some ella authors constraint. I havent confirmed it yet but i think it caused by models which while arent synced into db, they are loaded which gives some constraints in ORM which do not really exist in db.

**Comment by jan-matejka** [comment]
ad your comment on d2d784dd129ba7309ec121de8500bb7d5ed398eb

It looks neater on the first look but i'm not sure it is a good way.
get_publishable() will now return None only if ella.core isn't in INSTALED_APPS. If the Publishable model class can't be obtained it will raise an error.

If I just updated the line 44 how you suggest, it will silently continue even if get_model('core', 'publishable') will return None while ella.core is in INSTALLED_APPS

so I went with _get_publishable() in 20bfb9903a42c896e291c4c2d65133684918958e but I'm not really sure what The Rigth Thing is in here.

And while I was at it I took a look why Publishable is so special and I think it would be cleaner to do

```
if hasattr(model.__cache_ct__):
    model = model.__cache_ct__
```

in _get_key
and

```
if hasattr(model.__cache_object__) and callable(model.__cache_object__):
    return model.__cache_object__()
```

in get_cached_object
or so

And by looking at get_cached_object it looks to me like the Publishable objects are actually never cached. Am I wrong or is this correct behavior?

And is this line https://github.com/yaccz/ella/blob/feature/boxes_separation/ella/core/__init__.py#L5 really needed? It causes ella.core.models to be imported which messes up models by creating relations in ORM which doesn't really exist in the database. In case it is (needed), I'd add a setting that disables the line. Maybe it could even be dropped in next major version as as far I understand this method of adding templatetags to builtins is undocumented/generally frowned uppon.

**Comment by xaralis** [comment]
Publishable objects were cached by `get_cached_object` only when queried by PK (look at `Publishable.target` which is only a thin wrapper around `get_cached_object`), but it was finally fixed in acb7183.

**Comment by xaralis** [comment]
And just to share my opinion... It would be much simpler to write the boxes from scratch again than trying to extract them from Ella. In fact, they are very simple.

**Comment by jan-matejka** [comment]
Well, at first i suggested moving them into separate django app but it was met with resistance from Honza Kral and kvbik I think.

Ad rewriting, here i may just misunderstand what you mean but I dont see a reason to do rewrite it when we can just copy the code and polish it a bit.

**Comment by honzakral** [comment]
closing the ticket here, feel free to create a separate app and submit a pull request that will plug it into ella as long as the funtionality is the same.

Thanks
