### ISSUE TITLE
Unique Constraint of Listing Between Publishable and Category

### ISSUE THREAD

**Issue by andymccurdy** [ella/ella#105]
It seems to be that there should be a unique constraint on Listing on (publishable, category). Is there ever a use case where you'd want to list the same publishable in the same category?

**Comment by honzakral** [comment]
The use case is that you can have a limited promo (Listing with publish_to for example) and then another at different time. There should never be more than one Listing active in any category but in case you want to plan this ahead (and input the listings while creating the Publishable), you need to create two Listing instances in a category
