### ISSUE TITLE
Image from format not always right size

### ISSUE THREAD

**Issue by gpbmike** [ella/ella#111]
http://cl.ly/0U3P222S411d0S0s3A1q

The grid of images there should all be the same size, but you can see that the right edge isn't even.

Sometimes the image seems to be cropped a pixel less than the desired size. Happens with both the width and the height. Seems like a rounding error somewhere.

**Comment by honzakral** [comment]
@gpbmike could you send me those images? I cannot replicate it to debug it, an example would help.

Thanks!
