### ISSUE TITLE
ADMIN_MEDIA_PREFIX in ella.photos.admin

### ISSUE THREAD

**Issue by naro** [ella/ella#117]
Please replace ADMIN_MEDIA_PREFIX with STATIC_URL. Django1.4 admin fails on missing ADMIN_MEDIA_PREFIX settings.

https://github.com/ella/ella/blob/master/ella/photos/admin.py#L45

**Comment by whit** [comment]
This widget is really old and from 1st version of "extended" admin. I will solve it just by deleting this widget from basic admin.
