### ISSUE TITLE
Format name is not unique for same sites

### ISSUE THREAD

**Issue by whit** [ella/ella#138]
Now, you can save multiple formats with same name for same sites, which then raise error in template. Because it is more complicated to check format name and selected sites together, can I make format name unique?

**Comment by honzakral** [comment]
Please don't - if you need this, just add the check for the uniqueness with the sites, should be super simple with model validation.

**Comment by whit** [comment]
Ok, we will do it this way. Do you use same format names?

**Comment by honzakral** [comment]
No we don't. But I don't feel like there is never going to be a use-case for it and "because it is more complicated to check ..." is not a good reason for doing any changes. Especially when it's juat a piece of validation code that doesn't need to be super efficient nor complicated.

**Comment by honzakral** [comment]
lease do not commit stuff without tests. I will work on these.
