### ISSUE TITLE
Cache invalidation

### ISSUE THREAD

**Issue by honzakral** [ella/ella#139]
In d18e158b012706052c1701fce1cfa4b9742d296a I changed the box cache keys so they are prefixed by the key of the object (as used by `get_cached_object(Article, pk=42)`, which is how 90% interaction with the DB happens). I did this so that we can extend our very naive cache invalidation mechanism to be ever so slightly less naive. Since Django cache backends don't support deleting cache by prefix there are several options on how to proceed:
1. Use custom cache backend based on redis that could do `delete_by_prefix` (fallback to current limited behavior when method not present) (+ efficient, - enforces redis for cache, - doesn't play nice with others - subclasses, other backends, etc)
2. Store the keys related to an object in a redis list/zset and delete it manually (+ works on all backend, - lot of data potentially, - lot of boiler plate code would be required)
3. Version the key for indivual object - store the version number in cache, increment the number whenever save() is called (+ works on all backends, + not much additional code required, - additional GET from cache on most cache operations )

What do you think? I prefer solution 3, but I am interested in other people's opinions.

Once we get this in we can start doing other interesting stuff (have flatcomments invalidate all object's boxes for example) that will greatly improve responsivness of the site.

**Comment by andymccurdy** [comment]
I prefer option 3 as well. Have you considered storing the version number in the object's app data? This could be a completely separate, optional ella app that provides that app data container (for maintaining the version number) and at registration time, informs the ella cache utility to include the object version number in the cache keys.

If option 3 doesn't work for some reason, I think option 2 could work as well. I don't necessarily see why it would be a lot of boiler plate code -- seems like most of the changes would happen in ella.core.cache and likely won't bleed out beyond that module.

**Comment by honzakral** [comment]
@andymccurdy it won't work storing it in app_data - it would completely defeat the purpose of caching - having to retrieve the object to get the version number to be able to retrieve the object.....

I will start working on this tomorrow, if anybody disagrees, ping me. Thanks

**Comment by andymccurdy** [comment]
ya, good point :)

**Comment by xaralis** [comment]
I all in for proposal 3.
