### ISSUE TITLE
Proposal: Allow different number of objects on first category listing page

### ISSUE THREAD

**Issue by xaralis** [ella/ella#143]
Hi,

I am just surveying a little to see if someone is interested to accept following feature to the Ella core.

What we suggest is to allow to have different number of objects on first page of category listing than on following pages. The use case is mostly for homepages which tend to be different than article archives. This solution would allow the pagination not to skip/double any content which otherwise frequently happens because one is required to perform his custom listing on HP (with custom number of objects) and then the archive has to either start from first page (a major UX flaw) or start from page 2 and accept the truth that some articles might be doubled/missing in the list (a major UX flaw as well).

We have the code ready and I only seek approval to merge this to the core. No backwards incompatibility will occur since the default logic will stick to the current behavior of having same number of objects both on first page and all other pages. Proposed settings will be as simple as this:

``` python
# List 10 articles on HP.
CATEGORY_LISTINGS_ON_FIRST_PAGE = 10

# On other pages, list 20 articles per page.
CATEGORY_LISTINGS_PAGINATE_BY = 20
```

There is also support for AppData way of changing things per category.

**Comment by honzakral** [comment]
Hey, this makes sense to me, just want to see the code :)

**Comment by xaralis** [comment]
See the code now, especially deb8a2c0c8a661a7f07733c42f7a7f392194a3e6 :)

**Comment by xaralis** [comment]
Accepted...
