### ISSUE TITLE
created_on field for Publishables?

### ISSUE THREAD

**Issue by xaralis** [ella/ella#145]
Shouldn't we put created_on field back to Publishables?? There is quite strong need for sorting the objects by the creation date, especially for writers and editors...

**Comment by honzakral** [comment]
If you ask with "Shouldn't we ..." the answer is always no - without concrete use case that somebody needs it's pointless. You can always sort by PK to get the ordering you need.

**Comment by xaralis** [comment]
Well, the use case is quite clear. The editors expect it would be possible to sort content they are creating by time it was created, not published. It's simply because of the common workflow, the go from older records to the new ones. Sorting by publish date is not a solution since lot of content is created way before it is published.

**Comment by honzakral** [comment]
And what's wrong with sorting by pk? It would work for your use case. Alternatively you can sort by updated field.

**Comment by xaralis** [comment]
Ok, let's stick with pk for now... until there is a stronger need than this ;)
