### ISSUE TITLE
IntegrityError: (1062, "Duplicate entry 'XXX-XXX' for key 'photo_id'")

### ISSUE THREAD

**Issue by xaralis** [ella/ella#149]
When generating photos in format, there are times when integrity error is raised.

This is probably related to comment:

> use get or create because there is a possible race condition here
> we don't want to JUST use get_or_create to go through cache 99.9% of the time

on line 299 in `ella/photos/models.py`. I assume, it's not a big deal but we should more clever and do not report this as exception then.

**Comment by honzakral** [comment]
I still don't understand how get_or_create fails here. Imho it's because the save() takes a long time with generating the image, imho the solution is to provide either some sort of locking, separate those two processes (generate image, do get_or_create, if not created remove the image)

**Comment by xaralis** [comment]
I think it's very possible this happens, since there are no transactions. Yes, the likely cause is the long duration of save.

Locking would be non-trivial... to me, the simple solution would be to catch the exception and perform one more get to finally retrieve the result.

**Comment by xaralis** [comment]
Finally, I was able to find out, where the problem probably is, have a look here:

https://code.djangoproject.com/ticket/13906

Looks like it's MySQL only thing. Once again, I suggest adding one more get if this happens. Sounds good to you guys?

**Comment by honzakral** [comment]
Having repeatable read for a database is VERY weird idea. That said, one more get is fine with me since it will never run for any reasonable database.

**Comment by xaralis** [comment]
Strange, I have looked deeper in django implementation of `get_or_create` and it seems that it should handle the situation described, have a look:

``` python
    def get_or_create(self, **kwargs):
        """
        Looks up an object with the given kwargs, creating one if necessary.
        Returns a tuple of (object, created), where created is a boolean
        specifying whether an object was created.
        """
        assert kwargs, \
                'get_or_create() must be passed at least one keyword argument'
        defaults = kwargs.pop('defaults', {})
        lookup = kwargs.copy()
        for f in self.model._meta.fields:
            if f.attname in lookup:
                lookup[f.name] = lookup.pop(f.attname)
        try:
            self._for_write = True
            return self.get(**lookup), False
        except self.model.DoesNotExist:
            try:
                params = dict([(k, v) for k, v in kwargs.items() if '__' not in k])
                params.update(defaults)
                obj = self.model(**params)
                sid = transaction.savepoint(using=self.db)
                obj.save(force_insert=True, using=self.db)
                transaction.savepoint_commit(sid, using=self.db)
                return obj, True
            except IntegrityError, e:
                transaction.savepoint_rollback(sid, using=self.db)
                try:
                    return self.get(**lookup), False
                except self.model.DoesNotExist:
                    raise e
```

Especially, following lines:

``` python
            except IntegrityError, e:
                transaction.savepoint_rollback(sid, using=self.db)
                try:
                    return self.get(**lookup), False
                except self.model.DoesNotExist:
                    raise e
```

Looks like the Django should handle the IntegrityError by itself... What are we missing?

**Comment by xaralis** [comment]
Or maybe I just don't fully understand the ticket 13906 on django issue tracker..

**Comment by xaralis** [comment]
Eh... now I probably get it. Unfortunately, as far as I understand it, one more `get` will not make any difference since it would probably fail on `DoesNotExist` too (even though the record is already there). Because of that, I am now closing the issue since we basically can't fix it. Screw that MySQL really.
