### ISSUE TITLE
Format update fails to change (due to memory leaking) when it has lot of related FormatedPhoto

### ISSUE THREAD

**Issue by xaralis** [ella/ella#151]
It would be wise to perform cleanup iteratively (by few hundereds for example) and do a garbage collector cleanup prior to each iteration.

**Comment by xaralis** [comment]
Even better, it would be nice to perform this as background task if possible so that the application would not be wating minutes to respond...

**Comment by honzakral** [comment]
This is out of scope of Ella. If there is a memory leak, it's a bug in Django that needs to be fixed. Either way - Formats should not change, if you do so, you are on your own and should take the precautions based on your data.

**Comment by xaralis** [comment]
Well, while this might be true for advanced developers who can see to the inner parts of Ella it could be seen as bug for everyone else. If we don't try to solve this, we should mention it in the docs at least.
