### ISSUE TITLE
Does not support Django 1.5 custom user models

### ISSUE THREAD

**Issue by atkinson** [ella/ella#152]
Hello,

Just tried adding ella to a project and found that it imports contrib.auth.models.User.

Is there a branch or patch that supports Django 1.5 custom user models?

many thanks

**Comment by honzakral** [comment]
Hi, currently there is no branch and/or patch but it should be simple to implement - User is only used on the Author model so there is just one line that needs to change.

**Comment by atkinson** [comment]
That almost does it. Unfortunately the south migrations are hardwired to auth.User. I'm not sure there is any way around that except for deleting the migrations.

**Comment by honzakral** [comment]
@atkinson I believe the best solution here is for you to fake the migrations by running raw syncdb and then faking all.
