### ISSUE TITLE
Make slug field an unique field

### ISSUE THREAD

**Issue by mlen108** [ella/ella#154]
And greetings from DjangoCon :-)

**Comment by honzakral** [comment]
There is no need for the slug to be unique.

**Comment by mlen108** [comment]
As far as I can see there's a possibility of having below URLs
/2013/05/16/slug1
/2013/05/16/slug1
Which will cause problems, because slugs are not unique.
If you don't want to have them unique then you may consider make it unique together with other field(s) on model's Meta.

**Comment by whit** [comment]
It is checked in `Publishable.clean()`, so you should call this before saving.
