### ISSUE TITLE
More consistent Redis config for Ella

### ISSUE THREAD

**Issue by xaralis** [ella/ella#155]
In rediswrapper branch (922435a19b), I have updated the redis configuration settings variables. This makes the configuration more consistent with other Django settings and also enables some custom stuff like different Redis client class.

Can someone check it so that we can merge it to the master?

**Comment by whit** [comment]
I think, it should be backward compatible with deprecation warning, because as is, it's hidden change which silently broke running projects.

**Comment by honzakral** [comment]
In it's current form this is not merge-able. It forces people to type out everything because it doesn't respect the defaults and has other minor problems.

I like the idea of providing easier configuration, but this is both harder and more confusing

**Comment by xaralis** [comment]
Ok, i'll fix it up a little to be backwards compatible and have sensible defaults to save some writing.
