### ISSUE TITLE
Rotate image according to EXIF after uploading

### ISSUE THREAD

**Issue by xaralis** [ella/ella#159]
Since PIL removes EXIF data when saving the image, rotation recorded in EXIF is not preserved and some images are therefore wrongly rotated.

I made a fix in 7c7637c, can someone have a look at it if it's ok and eventually merge this into master? I know tests are probably necessary too.

**Comment by honzakral** [comment]
I believe that originals should be preserved as they are, but this would be useful when creating FormatedPhotos and either just transfer the exif information over or take it into account there.

**Comment by xaralis** [comment]
Well, I thought it would be better to rotate it immediately since it then complicates formatting (crop boxes and stuff). The problem is that PIL removes EXIF when doing it's changes...
