### ISSUE TITLE
When uploading images, they are converted to JPG no matter what was the original

### ISSUE THREAD

**Issue by xaralis** [ella/ella#20]
I am having trouble uploading transparent PNGs since after the upload, they are internally converted to the JPGs. This is really annoying since it is not possible to upload transparent images whatsoever.

Is that because of the Flash image editor?

**Comment by honzakral** [comment]
yep, the flash editor converts everything to jpeg _before_ uploading...

**Comment by xaralis** [comment]
That's really annoying... Is there any way we could disable this behaviour? At least for PNGs because it's sometimes handy to have transparency...

**Comment by honzakral** [comment]
Your guess is as good as mine: https://github.com/ella/centrum-photouploader

**Comment by xaralis** [comment]
Closing the issue as this flaw is not so serious and it's still possible to add PNG photo via pure django admin when needed
