### ISSUE TITLE
Mass-uploaded photos not added to gallery

### ISSUE THREAD

**Issue by Sixtease** [ella/ella#27]
/galleries/gallery/$n/ =>
Gallery Items =>
magnifier =>
Mass upload =>
select and upload photos =>
I'm returned to gallery edit page but the new photos are not automatically added to the gallery

**Comment by xaralis** [comment]
Doesn't work for me... No gallery is created, don't even see any code that could handle such a thing.

**Comment by Sixtease** [comment]
This ticket deals with adding photos to gallery which is being edited. I modified the title to explicate this. Creating a new gallery for mass-uploaded photos shall get a separate ticket.
