### ISSUE TITLE
Adding photos to new gallery doesn't work properly

### ISSUE THREAD

**Issue by xaralis** [ella/ella#28]
When creating galleries photos are not saved properly. Only the first image is saved, the rest is forgotten after form save.

When editing, it seems that it works correctly.

**Comment by Sixtease** [comment]
Seems to have the same cause as #29.

In /galleries/gallery/add/, there are two empty photos after load. Whereas the first one has ids like `id_galleryitem_set-0-*`, the second one has ids like `id_galleryitem_set-__prefix__-*`. Removing the second field from the incoming data structure should fix the bug.

**Comment by majerm** [comment]
fixed by 47983b6
