### ISSUE TITLE
Better RSS title

### ISSUE THREAD

**Issue by xaralis** [ella/ella#34]
Curretly it says **First X objects from category Y**. This doesn't sound very cool. Better would be bare name of category.

**Comment by martinbilek** [comment]
Maybe category "godlike JSONField", can be used for RSS title?

**Comment by xaralis** [comment]
It would be better to keep this as an attribute on category itself as exports are already in Ella core and therefore always present.

Does someone have any complains against putting `syndication_title` directly to the `Category` model?

**Comment by xaralis** [comment]
Finally solved by JSONField...
