### ISSUE TITLE
Drop support for multiple article contents

### ISSUE THREAD

**Issue by xaralis** [ella/ella#36]
This seems obsolete since even newman doesn't show more contents to fill up. Let's save some performance and move the articles_articlecontents to articles_article table.

To allow for multiple_contents, simple solution like in [ella_toolkit](https://github.com/fragaria/ella_toolkit/tree/master/ella_toolkit/articles/multiple_contents) can be used instead.

**Comment by honzakral** [comment]
yes please!

**Comment by honzakral** [comment]
done in cleanup

**Comment by whit** [comment]
Finished, tests passed, needs data migration in #53
