### ISSUE TITLE
Auto-create gallery for mass-uploaded photos

### ISSUE THREAD

**Issue by Sixtease** [ella/ella#37]
Gallery should be automatically created when adding photos by mass upload.

**Comment by xaralis** [comment]
This issue looks little redundant when you consider that #27 does really the same thing only from different point of view. I think, it can be closed.

**Comment by xaralis** [comment]
Would be nice if someone confirmed we can close this.

**Comment by Sixtease** [comment]
I don't think this and #27 are the same thing. In #27's scenario, you already have a gallery. Here, you just upload photos.

**Comment by xaralis** [comment]
Don't think so. You can easily do the same by adding blank gallery and in photo selection just trigger mass upload and photos will be created.

The title says that gallery should be created by mass upload and that's exactly what you achieve (only from gallery addition page) by doing what I described.

**Comment by Sixtease** [comment]
Well, if the user just goes to photo and does mass upload, without creating a gallery first, then the mass upload doesn't create a new gallery. So as I understand it, this ticket is not solved.

We can reject it and tell the users they should create a gallery themselves, or make it work. I guess it's a decision for product management or some such.

**Comment by xaralis** [comment]
Yes, you're right. However, I think that this kind of solution is even more flexible for users than one original proposed in this feature request. User doesn't always necesarilly need to create gallery. In present state, he has simple option but don't have to if not required.

I think that mass upload has its common use case when someone want's to create a gallery and save some time. So he adds title, author, etc. and then wants to upload all the photos in one run. That's exactly what is now possible.

As I said before, someone else is needed to confirm we can close this.

**Comment by martinbilek** [comment]
Ok, let's discuss it on Monday meeting, so I can understand this issue more from product point of view. Than we decide to close or update issue.

**Comment by xaralis** [comment]
So we finally agreed that the current mass-upload possibilities are satisfying and this issue can be therfore closed.
