### ISSUE TITLE
Major refactoring of photo formatting/thumbnailing

### ISSUE THREAD

**Issue by xaralis** [ella/ella#39]
We should use something like [sorl](https://github.com/sorl/sorl-thumbnail) instead of custom solution.

**Comment by honzakral** [comment]
I don't think we need this ATM - the formatting code is fine and does everything we need. If we decide that's not the case I would just propose extracting the photos app and making it virtual - just a bunch of code that will hide whatever backend (ella.photos, sorl, ...) behind a unified API (get_photo_in_format basically, that's imho all that's needed).

What, on the other hand, ella desperately needs is:
- play nice with django storage backends (we want to use it against S3)
- be moe efficient when dealing with the DB (done in cleanup branch where we can use redis to store the image info)
- remove thumbnail-specific code that is unnecesarily complex and baked-in when it doesn't have to be (#43)

**Comment by honzakral** [comment]
resolved all the issues I raised in cleanup, I don't feel we need anything more ATM
