### ISSUE TITLE
Can't "Add article" - window is locked

### ISSUE THREAD

**Issue by alek2** [ella/ella#4]
When click to "Articles -> New article" I see modal window "Loading media..." and nothing happening. Main window where I can enter title, metadata, etc. is locked by this modal window.

Can I give you some debug logs to figure out the problem?

Thanks.

**Comment by whit** [comment]
Hi alek2. Some debug output you can se in Firefox/Firebug console. Check your urls and settings (ADMIN_MEDIA_PREFIX and NEWMAN_MEDIA_PREFIX).

In near future we will add timeout to loading media.

**Comment by Almad** [comment]
This is known bug with django 1.2, should be fixed soon with 1.2 support.

**Comment by whit** [comment]
Fixed in django-1.3 branch.
