### ISSUE TITLE
Mass upload don't work, it raises 403

### ISSUE THREAD

**Issue by whit** [ella/ella#44]
There is some csrf related issue. When csrf check is turned off for upload function, it upload files as expected.

**Comment by Sixtease** [comment]
How do I switch the check?

**Comment by Sixtease** [comment]
Flash wipes out the csrf cookie from the upload requests. I can send the value of the cookie along in the POST data. However, I'm not sure how this is supposed to protect the app from CSRF. According to [docs](https://docs.djangoproject.com/en/1.3/ref/contrib/csrf/), the value should be a [nonce](http://en.wikipedia.org/wiki/Cryptographic_nonce) but it seems to stay the same request after request. The same repeated value is sent as a cookie and as a post parameter and then (correct me if I'm wrong) compared against each other.

Can someone (maybe @HonzaKral ?) explain to me how this is supposed to protect anybody from cross-site request forgery?

**Update**: I just tried out to change the cookie and the _csrfmiddlewaretoken_ input field to a different value with Firebug. The request was accepted.

**Comment by xaralis** [comment]
From the Django docs:

> How it works
> 
> The CSRF protection is based on the following things:
> 
> A CSRF cookie that is set to a random value (a session independent nonce, as it is called), which other sites will not have access to.
> 
> This cookie is set by CsrfViewMiddleware. It is meant to be permanent, but since there is no way to set a cookie that never expires, it is sent with every response that has called django.middleware.csrf.get_token() (the function used internally to retrieve the CSRF token).
> 
> A hidden form field with the name 'csrfmiddlewaretoken' present in all outgoing POST forms. The value of this field is the value of the CSRF cookie.
> 
> This part is done by the template tag (and with the legacy method, it is done by CsrfResponseMiddleware).
> 
> For all incoming POST requests, a CSRF cookie must be present, and the 'csrfmiddlewaretoken' field must be present and correct. If it isn't, the user will get a 403 error.
> 
> This check is done by CsrfViewMiddleware.
> 
> In addition, for HTTPS requests, strict referer checking is done by CsrfViewMiddleware. This is necessary to address a Man-In-The-Middle attack that is possible under HTTPS when using a session independent nonce, due to the fact that HTTP 'Set-Cookie' headers are (unfortunately) accepted by clients that are talking to a site under HTTPS. (Referer checking is not done for HTTP requests because the presence of the Referer header is not reliable enough under HTTP.)
> 
> This ensures that only forms that have originated from your Web site can be used to POST data back.
> 
> It deliberately only targets HTTP POST requests (and the corresponding POST forms). GET requests ought never to have any potentially dangerous side effects (see 9.1.1 Safe Methods, HTTP 1.1, RFC 2616), and so a CSRF attack with a GET request ought to be harmless.
> 
> CsrfResponseMiddleware checks the Content-Type before modifying the response, and only pages that are served as 'text/html' or 'application/xml+xhtml' are modified.

I originally also thought, the it should differ from request to request. But it seems, that it simply persists for the session and it's sufficent as it's stored in session data which are not reachable for other domains. If we never sent them this CSRF token, they will not be able to perform CSRF reply attack.

If it passes even when you fill it up with different value, this mostl likely mean that you still have forgotten a **csrf_exempt** decorator in the upload view. Please check again and try it. If it won't be working by POST, we have to find another way...

**Comment by xaralis** [comment]
@Sixtease please switch to **proposals/2.1.0** branch and commit only there... We are in final phase and all 2.1.0 related stuff should go to proposals first and then merge it to master after that. Looks like you did something in the master (70800c8).

**Comment by Sixtease** [comment]
@whit yes, I had read that. I thought it through and came to the conclusion that it can actually work, though IMO the fact that the cookie doesn't change makes it quite weak.

@xaralis oh, OK, I'll switch to proposals/2.1.0 then.

**Comment by Sixtease** [comment]
I was working on a solution where the csrf token would be stored on the server side for the time of mass upload and the value sent in the upload form would be compared to that value. There's a fundamental problem with the fact that there's no way to trace the file upload to the session. The session cookie is gone as well. If I send the session ID in POST as well, can we access the session data without the cookie? Or is there a better way that eludes me?

**Comment by xaralis** [comment]
Hey, everybody stop working on this.

I think the current functionality is quite sufficent. What is more, big changes in required behaviour for this feature are on the way so it would be contraproductive to keep polishing this up.

Can we simply close this? It is the only issue blocking of 2.1.0 relase.

**Comment by xaralis** [comment]
Closing due to superior solution coming in.
