### ISSUE TITLE
Remove newman into separate app

### ISSUE THREAD

**Issue by honzakral** [ella/ella#45]
Create an ella/newman repo and move newman there. 

We can keep all the `newman_admin.py` files in ella for the time being although I would love for them to move into newman as well in the future.

This would simplify deployment and development greatly - it would reduce the number of requirements for ella, stabilize it's development process (no reason why newman's dev cycle should be bound to that of ella).

If done right (the app within newman would still be called newman), we can avoid having to create migrations as the table names will remain the same.

I would be more than happy if we still had the opton to use newman for ella, we could point to it in the docs etc. We can alway move the newman-specific part of the docs with newman and I would be happy to help with integrating those.

**Comment by xaralis** [comment]
We **definitely agree**. The sooner we do this, the better.

After all, there should be some newman replacement ASAP. Simpler, focused **only on writers/editors**. As we know by now, they use maybe 10% of what newman is capable of. The rest can be handled by common django admin anyway.

**Comment by honzakral** [comment]
Done, welcome to new newman repo. I tried to move all the tests as well but have no idea wheather the JS tests work at all.
