### ISSUE TITLE
Update the tutorial to reflect butchered ella

### ISSUE THREAD

**Issue by honzakral** [ella/ella#47]
Let's go through the tutorial and shorten it a bit - just enough so that any djangista can get ella up and running in 10 minutes with basic understanding of basic concepts (Publishable, Listing and Box).

**Comment by xaralis** [comment]
Yes, definitely needed ASAP.

**Comment by xaralis** [comment]
I have refactored the docs a bit. You can check it in 8d34e46. It's definitely not the final state, but I think it's sufficent at the moment.

**Comment by xaralis** [comment]
Can be closed, look at the docs.
