### ISSUE TITLE
Remove/split Polls

### ISSUE THREAD

**Issue by honzakral** [ella/ella#50]
it would be nice if we could get the polls app into a separate repo and maybe split the Poll/Contest/Quiz models into several different apps. Maybe cleanup and denormalize the models in the process.

**Comment by xaralis** [comment]
We vote for splitting and keeping this module. The best would be to use a different poll app (there's a bunch of them for Django), but that would require to make a **wrapper for double render support** which looks like too much work by now.

So, keep it (rot). When there's time, swich to different app?

**Comment by honzakral** [comment]
ok, let's leave this one be for the time being, closing it until we have an idea where to go with it...
