### ISSUE TITLE
Data migration script from Ella 2.x to cleanup branch (3.x)

### ISSUE THREAD

**Issue by whit** [ella/ella#53]
When models in cleanup branch to be a bit stable, create external script to migrate data.
- aricle contents ( and markup source texts update) -> article
- placement -> publishable (with "published" bool)

**Comment by xaralis** [comment]
We can provide migration for multiple contents.

Can @HonzaKral do the same for publishable-placement merge?

**Comment by xaralis** [comment]
There is already a migration for articlecontents in cleanup branch, I just polished other migrations a bit (removed old CH specific), see 1995558f493d878db259d54875f974daaaa2a994.

**Comment by honzakral** [comment]
the old one wasn't CH specific and was needed for migrations to run.

I am 100% for removing all the migrations and starting with just inital ones (newly created).

I added the publishable-placement migrations to core, those should work or at least provide a good starting point to fix those.

**Comment by xaralis** [comment]
Why do we need migrations like `core/migrations/0002_03_move_publishable_data.py` ? I don't see any reason for keeping them. I thought we would only provide migrations from **2.0.0** version which is expected to have all of these done already.

**Comment by honzakral** [comment]
we are using the code, without this migration the code will not run, syncdb & migrate will produce incorrect table. Either we remove all the migrations and chacne the initial one to reflect current state or we need this migration.

**Comment by xaralis** [comment]
And why is that so? We should create initial migrations from the state of proposals/2.1.0 branch and than aditional migrations all the way up to the state of current cleanup branch. If we create the initials from 2.1.0, there should be no problems with incorrect tables.

**Comment by honzakral** [comment]
yes, but until we do so, we need this one migration :)

**Comment by xaralis** [comment]
Ok, i'll try to work on this during the day. Now doing the same thing for galleries..

**Comment by xaralis** [comment]
Done :) Initial migrations for following apps now capture state of master branch and following migrations only contain changes in cleanup branch:
- articles
- core
- photos

This means that migration from 2.1.0 should be possible by something like:

``` bash
echo "TRUNCATE TABLE south_migrationhistory;" | django-admin.py dbshell
django-admin.py migrate 0001 --fake
django-admin.py migrate
```

**Comment by xaralis** [comment]
Closing the issue as it seems to be resolved. Migrations for Ella plugins should be discussed in their own repo issue lists.

**Comment by honzakral** [comment]
hmm, except articles which are completely unusable with initial migration unchanged and the important migrations removed.
