### ISSUE TITLE
Simple admin interface for writers/editors

### ISSUE THREAD

**Issue by xaralis** [ella/ella#54]
There should be simple interface for writers/editors. Not newman, but something forged specifically for them. Lightweight, not build on Django admin, customized only for them.

Newman is not sufficent, because it's just way too puffy. Most of writers use only articles + photos/galleries.

We need to discuss the basis of implementation though. In my point of view, it has to be javascript-heavy frontend as user-friendly as possible.

**Comment by HonzaMikula** [comment]
I don't think it's good idea. Better approach is to make Newman more customizable and work on Newmans UX. It would be good if Newman had something like individual themes for writers, editors, admins and so on. Every themes would point out the essential function for the specific role. For example writers theme would be mainly about articles, photos and so on.

I am afraid if we build new lightweight admin for wirters/editors they would constantly ask for all function they already got in Newman. And this lightweight admin in time will become same puffy as Newman or writers/editors will not use this lightweight admin.

**Comment by xaralis** [comment]
Well, the thing you propose is nice, but it has a major catch. Massive newman customizations is close to impossible due to inherent dependency on architecture defined by django admin.

The lightweight UI is not meant to be a newman replacement. It is supposed to be UI for writers/editors only. The rest can be achieved by running newman/django admin instance aside of this proposed UI.

**Comment by xaralis** [comment]
And I almost forgot to mention that newman code base smells like sh**... No docs, hard to read and JavaScript sources simply a mess. It would be really challenging to keep the newman rolling without a major rewrite anyway...

**Comment by Sixtease** [comment]
I'll be delighted to be a part of this. I'm leaving Prague tomorrow though, and will get back probably on Thursday February 2nd in the afternoon. Can the initial meeting wait until then?

**Comment by xaralis** [comment]
Proposed tools/frameworks:

django-tastypie for backend REST api
jQuery, require.js, underscore.js and backbone.js for rich JS client

What do you think? I have been doing quite a research through currently available JS technologies and this combination looks promising. And it plays very nicely with django-tastypie too (tried that myself).

**Comment by xaralis** [comment]
As second alternative for client side, we should consider Google Closure... It's well documented and thanks to Google, it's stable and development is ensured.

**Comment by Sixtease** [comment]
And, as far as I've seen, it has some really verbose and programmer-unfriendly Java-like APIs. I'm not eager to learn that to be honest.

**Comment by xaralis** [comment]
What I like about it is that it's full-featured library covering everything what is needed in contrary with previous suggestion which is composed from several parts. They do work well together, but the learning curve is slower due to the need to glue them up, I guess ...

**Comment by Sixtease** [comment]
I concur that it's good to have everything in one consistent, well-maintained tool. But I don't know about the learning curve. I think I can start using require+underscore+backbone more or less immediately. To boot, if we use closure, we'd likely kick jQuery out, so everything that jQuery does, I'd have to learn anew.

**Comment by xaralis** [comment]
Nice comparison:

http://codebrief.com/2012/01/the-top-10-javascript-mvc-frameworks-reviewed/

Especially useful to read the comments below the post too.

Ember.js is the winner BTW.

**Comment by Sixtease** [comment]
Yup, I had read that.

**Comment by xaralis** [comment]
As for HTML design side, I propose using Twitter's Bootstrap, it nicely wraps everything needed, see it in action http://domain7.com/mobile/tools/bootstrap/responsive/.

Moreover, it works with less.css which is very interesting all alone from my point of view.

**Comment by xaralis** [comment]
Big advantage is we can start with UX compliant tools from scratch and don't need a custom design while keeping it simple to make the pages look nice.

**Comment by Sixtease** [comment]
Yes, I'm all for using Bootstrap and Less

**Comment by xaralis** [comment]
Here is a nice data grid solution, which is made up on jQuery and compatible with Twitter Bootstrap 2.0:

http://datatables.net/index
http://datatables.net/blog/Twitter_Bootstrap_2

**Comment by xaralis** [comment]
Also, there is a jsfiddle example how to integrate it with Knockout.js:

http://jsfiddle.net/bdetchison/9BbgN/40/

Responsible library is : https://github.com/CogShift/Knockout.Extensions

**Comment by xaralis** [comment]
Please move all relevant discussion to two new repositories:

https://github.com/ella/ella-scribble - supposed to hold JavaScript application
https://github.com/ella/ella-api - supposed to hold Django-tastypie API
