### ISSUE TITLE
Add a generic JSONField to Publishable to store project-specific metadata

### ISSUE THREAD

**Issue by honzakral** [ella/ella#57]
Almost every application I have seen on ella has some need for added flexibility. I propose we add an optional JSONField to Publishable that individual plug-ins and projects can use to store their specific stuff. Some examples:
- store comment count with publishable
- tag lists
- importance
- source information (commercial, licence)
- template used to render
- ....

I also believe some conventions (a two line note in help_text fo the fields sounds enough) should be in place to provide namespaces (for example store your stuff under "app_name", for example:

{
  'comments': {'count': 12, 'latest': '20120128'},
  'tagging': {'public_tags': ['summer'], 'editorial_tags': ['white bikiny']}
}

**Comment by xaralis** [comment]
Yep, that sounds nice. We might create some accessors for the field that handle the namespaces for us... Like:

``` python
>>> p = Publishable.objects.get(pk=1)
>>> p.get_meta('tagging', 'public_tags')
>>> ['summer']
>>> p.set_meta('tagging', 'editorial_tags', ['white bikiny'])
>>> p.save()
>>> p.get_meta('tagging')
>>> {'public_tags': ['summer'], 'editorial_tags': ['white bikiny']}
```

**Comment by xaralis** [comment]
This looks like an simple yet functional JSONField implementation we can use:

https://github.com/bradjasper/django-jsonfield

**Comment by martinbilek** [comment]
JSONField sounds good to me. Also other models should use JSONField, for example category to store informations like "meta-description", "browser-title", "link-title"...

**Comment by honzakral** [comment]
OK, I will take care of this today, at least now I would like to avoid constructing a special interface for this - I learned the hard way (by deleting 20k+ LOC from ella that were mostly mine/my decision) that the simplest way is the best by far ;)

let's see how useful it is with just the field and add the methods later only if we find we absolutely need them.

**Comment by xaralis** [comment]
Please, add JSONField to category model too.
