### ISSUE TITLE
Fix inheritance of HTML templates

### ISSUE THREAD

**Issue by HonzaMikula** [ella/ella#58]
There is an issue. I've got web with 4 main categories (A, B, C, D). Every main category has another subcategories. Because category D is special (looks completely different), I need  separate template. Separate template is in page/category/D/category.html. But I have also subcategories (D1, D2, D3,..) which I want to look exactly as parent - category D. So I need to create separate templates for each subcategory. Subcategory template only content something like this

 {% extends "page/category/D/category.html" %}

It's really mess in file system and you need to create separate subcategory template every time you add new subcategory. So the editor is depend on developer and deploying process. It's not good.

Ella should search even in tree_path of category. Something very similar is working in positions. If it works, there would be only one separate template for category D and subcategories D1, D2, D3,.. would use template of parent category D.

**Comment by martinbilek** [comment]
I can imagine situation, where you need to override only parent category, not it's subcategories. But from my experience 99% template needs to be similar in whole category branch/tree - as @HonzaMikula propose.

What others think about it?

**Comment by honzakral** [comment]
I can get behind that. It would have some negative performance impact, so I designed https://github.com/WhiskeyMedia/django-templatefinder to help with that.

**Comment by xaralis** [comment]
Using cached template finder to get rid of perf troubles, I don't see a reason why not doing it the way @HonzaMikula proposed, it makes sense and I think this behavior is kinda expected when designing the templates.
