### ISSUE TITLE
Provide a way for better URLs for static pages (static articles)

### ISSUE THREAD

**Issue by xaralis** [ella/ella#59]
Very often we struggle with "nice URLs" that categories are blocking. This is mostly the case for static pages like contact page, usage conditions and so on.

In some other CMS product, we have seen nice solution which allowed to select different behaviours for different categories. Most interesting are: **article listing** and **showing detail of specified article**. A feature like this would solve our URL issue.

So far, there are several ways how to handle such pages in Ella, but none of them is pleasant.

1) Someone will probably argue that such a function is already available using static articles (or static placements before cleanup started). This is true but static articles' URL just sucks. We don't like having `/static/` prefix in URL just because the CMS doesn't know how to do it properly.

2) Using category description to contain HTML to render the page. This smells on the first sight.

3) Put all the HTML in category template. This isn't nice too because you cannot alter the HTML from administration, nor you can change the behaviour of this given category if requested without help of developer.

As you can see, nice solution is missing. This kind of behavior doesn't necessarily need to be in Ella's core, but I would really appreciate if we can find out some nice way how to do this (an app which uses category metadata JSONField and overrides urls file and category detail?).

**Comment by whit** [comment]
I think it's not necessary, not now. You forgot two better ways:
- Positions
- Standard listing

To illustrate, look at http://ranchbystra.cz example, it can be done easily and quickly (there is `listing 1` version). Editors also don't have problem to edit things, they can use standard way.

EDIT: In all solutions, effort will be roughly the same, always have to prepare a customized template...

**Comment by xaralis** [comment]
Using positions for this is awful mess. `listing 1` sounds better yet it still looks unclean :( But it can wait, of course.

**Comment by martinbilek** [comment]
After discussion with @xaralis it's now enough to use JSONField on category to store information like "category listing 1", "normal listing". Than another app can override category URLs to resolve what we need.

Than please @HonzaKral add JSONField on category too ;)

**Comment by kvbik** [comment]
you should create simple app, that will bind nice url and a placement.
this app will be in `urls.py` before `ella.core.urls`.

how about that?

**Comment by xaralis** [comment]
@martinbilek JSONField on category is already in there :)

@kvbik That's mostly what I had in mind althought it should be more generic to enable admin editing.

**Comment by honzakral** [comment]
btw I am all for changing the static placement URL - what about `/category/sub/ARTICLE_ID-article-slug/` ? I would be all for that. I used to really hate the idea of numeric IDs in the URL but there is really nothing wrong with it if done properly.

other than that let's close this issue due to the posibility to add this info to `app_data`

**Comment by xaralis** [comment]
Together with @martinbilek and @whit we have agreed on this solution:
- we will add a rich-text `content` field on `Category` model
- in settings, it will become possible to define a list of templates that can be used to render a category detail
- for each category, site administrator/developer will be able to select which template is used to render a category (one more field to define on `Category` model)
- template fallback will remain same, only the template name can be different from `category.html` if previous note takes place

These ehnacements add lot of flexibility that can easily be used to create a `static_page.html` template used to render category as static page while keeping nice administration of content using the `content` field. But there is lot more, one can think of different layouts for categories. This is simple a really cool.
