### ISSUE TITLE
Undocumented requirement anyjson

### ISSUE THREAD

**Issue by ipmb** [ella/ella#6]
Couldn't syncdb until I ran the following:

```
pip install anyjson
```

**Comment by Almad** [comment]
Sorry for not respondign - we have pending ticket for writing up whole requirements.txt, should be in master soon.

**Comment by Almad** [comment]
Our auto-push system is currently not working, so sorry to let you wait.

**Comment by pykler** [comment]
I ran into this issue just now following your tutorial.
