### ISSUE TITLE
Priority of objects in category listing

### ISSUE THREAD

**Issue by HonzaMikula** [ella/ella#61]
Now ella prioritize objects in category listing by date & time of placement. Problem is that placement also control when the object is visible in category.

Common case is that editor wants to everyday publish new objects but he also want to keep old object on top of listing, because the object really work and users click on it. Here is the example:

0 day order of articles: A, B, C, D
1 day order of articles: A, E, F, G, B, C, D

There is no easy way for editors how to do that. In Newman there should be one page, where editors easily see (and of course simply change)  order of objects for specific time and specific category.

**Comment by whit** [comment]
Ordering is based on `Listing` datetime, not on `Placement` (`Publishable` in cleanup branch). So you can have older object  listed first in category. But i agree, in admin is no comfortable way.

**Comment by honzakral** [comment]
I agree that we have no way of doing this. I would also say that there _is_ no good way of doing this. It either requires too much discipline on the side of the editorial team (never going to happen) or some complicated logic that will ultimately work only for limited use cases.

My gut feeling here is leave this to plug-ins - listings is just a templatetag, you can override it or just supply and use your own that uses something else - we will probably roll our own priority system based on redis for our next project for example.

**Comment by honzakral** [comment]
I am closing this, see #76 for a proposed backwards compatible solution.
