### ISSUE TITLE
Get rid of Format model

### ISSUE THREAD

**Issue by xaralis** [ella/ella#62]
On today's meeting with @martinbilek  and @whit we agreed that it will be nice to get rid of photo format altogether and switch to Django settings-based formats. There nothing really useful about the way photo formats are defined as it's usually done only once during the site lifecycle - at the time the site is built.

By using settings-based formats, we will save some DB queries and it will be much simpler to manage the list of formats.

**Comment by honzakral** [comment]
I am strongly against this for several reasons:
- we use the format ID everywhere and across sites, how do you synchronize settings for multiple projects?
- I really don't want designers in my settings.py or anywhere near python but I really don't want them to bother me to create a Format for them either
- how do you then make sure you can share images across sites?
- if you want to define them once in code, use fixtures and you lose nothing from the functionality.

how about we just cache all the formats in memory? Do something like Format.objects.get_for_name() which would have similar caching logic as Django ContentType's get_for_id(). I wanted to do that anyways. Also note that when you use cached template loader all the {% img %} tags will load their format on compile time so the Format is cached in memory even now for majority of use cases.

**Comment by honzakral** [comment]
I am closing this. I can see why somebody would want a simpler way of creating thumbnails and am not against that at all, but if we decide we want anything like that, let's built it next to the existing solution which actually works very well for a lot of use cases.
