### ISSUE TITLE
Shorter URLs for static Publishables

### ISSUE THREAD

**Issue by honzakral** [ella/ella#63]
I propose we use `/category/sub/articles/123-article-slug/` as a URL for an Article with static=True

if nobody has serious complains I will go ahead and implement it tomorrow.

**Comment by xaralis** [comment]
No compaints here. Just wondering, do you mean it that only for articles? This covers all publishable objects with static placement, right?

**Comment by honzakral** [comment]
Great. Absolutely for all publishables.
