### ISSUE TITLE
Newman's address stack is broken (handler priority bug)

### ISSUE THREAD

**Issue by Sixtease** [ella/ella#66]
When adding to NewmanLib.ADR_STACK (which controls, where a change form redirects after save), the _from_ field is sometimes incorrectly set to the new address.

This looks like the handler that sends the page to the new address is called before the address stack is pushed to, so the information about where we come from is already lost.

The code involved is in
- `ella/newman/static/newman/js/related_lookup.js` in function default_adrstack_push_callback
- and `ella/newman/static/newman/js/kobayashi.js` in handlers commented `// Set up event handlers`

**Comment by xaralis** [comment]
We should discuss personally what's causing this and where to fix it.

**Comment by Sixtease** [comment]
I have it fixed already, I'll push it when I push the mass uploader.
