### ISSUE TITLE
Newman's gallery - can't add more than two photos into gallery items

### ISSUE THREAD

**Issue by jezradek** [ella/ella#68]
There is a bug in newman's gallery. You can't add more than two photos into gallery items.

**Comment by whit** [comment]
Can I know current status of this bug? Is blocking us to move closer to 3.x.

**Comment by jezradek** [comment]
Dne 10.2.2012 08:05, Vítek Pliska napsal(a):

**Comment by Sixtease** [comment]
@jezradek Please test

**Comment by jezradek** [comment]
TITLE:

Release 2012-02-20

PROC (seznam zmen):
     Prechod na novou verzi Elly-2.0.5, Djanga-1.3.1

BALICKY:
     daz-web
     daz-static
     daz-cron

KDE:
    dev4.sanoma.cz:/var/local/debian/dists/stable/main/binary-amd64/daz-*_0.1.73_all.deb

POSTUP:
1/ Instalace balicku

# apt-get install daz-web daz-static daz-cron

2/ Zkontrolovat config a to hlavne proxy, db a memcache

3/ Restart

# svc -d /service/daz-websystem_http

# svc -u /service/daz-websystem_http

4/ Zkontrolovat zdali mi poslouchaji porty

# netstat -nlp | grep 97

5/ OK

6/ TEST

http://www.dumazahrada.cz
http://www.dumazahrada.cz/zasilani-novinek
