### ISSUE TITLE
django.views.generic.simple.redirect_to can not be used with ellas custom url resolver

### ISSUE THREAD

**Issue by jan-matejka** [ella/ella#7]
redirect_to expets url argument to be a str whereas custom resolver passes context in there, i guess

**Comment by xaralis** [comment]
Please can you describe a situation when this doesn't work as expected? This doesn't look like major design flaw anyway since it needs more information than simple urlconf usually has...

**Comment by honzakral** [comment]
This makes no sense - redirect_to expects a URL which you can easil get from custom url reolver. Closing as won't fix

**Comment by jan-matejka** [comment]
The issue arises when you want to derive EllaCoreView and your get_context takes additional args. You need to also modify **call** in the very same way which wouldn't be neccesary if **call** took *args and passed it to get_context

**Comment by jan-matejka** [comment]
**call** was supposted to be __call__

**Comment by honzakral** [comment]
EllaCoreView's __call__ and get_context take **kwargs, which is perfectly suited to what you need, just name your params.
