### ISSUE TITLE
Newman's responses are shown out of newman app

### ISSUE THREAD

**Issue by jezradek** [ella/ella#72]
If you add or edit some object e.g. article or photo via newman. A response for this action is shown on your website. The response is gone after refresh.

See:
http://uloz.to/xcycL8b/response-out-newman-png

**Comment by xaralis** [comment]
This is nothing serious: https://docs.djangoproject.com/en/dev/ref/contrib/messages/#behavior-of-parallel-requests.

Most likely, it is caused by newman not pulling the created messages like here: https://docs.djangoproject.com/en/dev/ref/contrib/messages/#displaying-messages.

**Comment by jezradek** [comment]
I agree and just wanted you to know.

**Comment by xaralis** [comment]
This is easily solved by proper configuration and I am therfore closing this.

FYI, you need to ensure the session is not shared by admin and client side of installation. For example, this can be done by using `SESSION_COOKIE_DOMAIN` setting.

**Comment by whit** [comment]
You need same session for editors to allow preview non published articles on frontend... But keep it closed, it's a small thing.

**Comment by xaralis** [comment]
Ah, you're right, I forgot. Shame on me.
