### ISSUE TITLE
http 500 error code in calendar

### ISSUE THREAD

**Issue by peterMikulec** [ella/ella#85]
500 error code is present when you click to random date in calendar at home page:

DatabaseError at /newman/core/publishable/
date/time field value out of range: "0-01-01 00:00:00"
LINE 1: ... 11 AND "core_publishable"."publish_from" BETWEEN E'0-01-01 ...
                                                             ^
HINT:  Perhaps you need a different "datestyle" setting.

**Comment by Sixtease** [comment]
Works for me -- please specify the reproduction scenario more exactly.

**Comment by peterMikulec** [comment]
there is a calendar on the left side in home page, just try to select one day(click to one day) there should be a list of publications, but HTTP 500 is thrown

**Comment by Sixtease** [comment]
Yes, sorry, I didn't see the 500 error probably because I use a different DB backend. The date is set wrongly anyway.

**Comment by Sixtease** [comment]
Fixed in proposals/2.1.0
