### ISSUE TITLE
Remove the content_type_name from URL

### ISSUE THREAD

**Issue by honzakral** [ella/ella#93]
This is no longer needed, it's not welcome because of SEO and makes the url too long, I believe we should remove it and provide a migration for backwards compatibilty that would create Redirect objects for every instance of this.

**Comment by whit** [comment]
No problem with this but I prefer simple redirect middleware than many redirect records in db.

**Comment by honzakral** [comment]
that's good idea, I will create a middleware with the list of regexes for the old schema that will do 301 redirects

**Comment by honzakral** [comment]
Implemented in issue-93 branch (4e7881bc86cbcd91fabe3546cf4a3d5f80626edf)

**Comment by martinbilek** [comment]
Great!

**Comment by honzakral** [comment]
done and merged, works on tested.com
